* tsq paper
** draft

*** sketch
Are there, could there be, any way of surfacing body narratives in
heterosexual, cisgendered stories?

How might these investments connect the anti-trans and trans
perspectives?

Machine learning ideal tool for studying normativity: a tool for
finding the shared, the average, the obvious.

Close reading analysis:
- Question -- how does the presence of the visual body affect dating?
- Answer -- body perception splits, bodily sensation flows and ebbs. 

Naomi's notes:
- Reader must be invested in the reading method.
- The technical process is a heuristic.
- Add a few sentences summarizing the technical process before going
  into details.
- Scene setting in the beginning. The tendencies of language. 
*** outline
- toward a new method of reading
  - AIDs crisis: what kind of knowledge can help deveop politics. 
  - reading normativity, looking for shared investments.
- close reading: machine learning
  - the training process toward approximation
  - hallucination and overfitting (when there isn't enough data)
- close reading: LiB
  - person splits from visual in the pod
    - Prosser on body image split from material body
    - "my body" activates sensorium of feelings
    - touch is more direct?
  - postpods,
    - the body collapses into the visual
    - touch becomes repulsive
    - future fatigue sets in
    
- trans studies on normativity
  - Chu: requires that we understand normativity
  - Prosser: on narratives of embodiment, coming back to the body
  - Malatino: attachments to the future

*** toward a new reading practice for normativity
Reflecting on the AIDS crisis, Queer Studies scholar Eve Kosofsky
Sedgwick questions the point of reading and of knowledge gathering in
general for politics. She explains that certain types of knowledge,
especially knowledge of systematic oppression, injustice, and
discrimination: she asks, "what does knoweldge do, the pursuit of it,
the having and exposing of it, the receiving-again of knowledge one
arlready knows?" (/Novel Gazing/ 3). She clarifies that, "for someone
to have an unmystified, angry view of large and genuinely systemic
oppressions does not /instrinsically/ or /necessarily/ enjoin that
person to any specific train of epistemological or narrative
consequences” (/Novel Gazing/ 3). In other words, this kind of
analysis does not convince people of anything they don't already know.

In our modern day, where outrage seems to be self-generating, we seem
to be in an accelerated situation on the question of reading.

This paper is about developing a way of reading normativity, and using
normativity as a focus and a method for finding shared investments and
common ground between seemingly opposed groups---cis and trans. The
readings here are centered on cis experiences, which I read through
the lens of Trans Studies theorizing on normativity.

The object of my study is a reality TV show, /Love Is Blind/ (/LiB/),
which puts participants into a dating experiment where they cannot see
their partner until they have both agreed to get married. The show
contains two stages, the pre-engagement stage, where participants date
each other from separate “pods” where they can hear but not see the
other, and engagement stage, where participants finally meet and
proceed to live together in preparation for the wedding.

In partitioning the romantic experiment into pre-engagement and
engagement segments, the show necessarily poses the presence and role
of the body as the dependent variable that ultimately determines the
viability of long-term commitment. In other words, it sets up
perfectly an examination of how the body may affect normative
trajectories and desires. It allows me to ask two central questions:
first, how does desire emerge when you foreclose the physical body?
sAnd how does this desire change when you introduce the physical body?

To analyze these shifts, I read transcripts from the show. In doing
so, however, I experiment with a new form of close reading that does
not expose, describe, or constellate text—to name some common verbs
used to illustrate close reading analysis. Rather, I use a method that
allows me to study the most normative perspectives expressed by the
characters on the show.

To do so, I use a text generator that picks up common and shared
feelings and desires from the characters in the show. First, I feed
examples of text culled from the show's transcripts into the text
generator. From processing these examples, the tool absorbs patterns
in language use, so it can "learn" how characters talk about certain
topics like love, desire, and the body. It then uses these patterns
from the text to make educated guesses on how to respond to questions
about the body and its role in the couples' romantic plot. This
process, which is highly techical (and explained in detail below),
allows me to surface common perspectives and experiences from the
characters on the show. It is a tool for normalizing language
expression into average forms. It is a tool, in other words, for
exploring normativity.

*** trans studies on normativity, body splits, future fatigue
To explore the desire for normativity, I borrow from ideas in Trans
Studies. Andrea Long Chu points out that Trans Studies "requires that
we understand–-as we never have before–-what it means to be attached
to a norm, by desire, by habit, by survival" ("After Trans Studies"
108).

Specifically, I borrow from ideas about the body. I am interested in
how the body figures into trajectories of normativity, which, in the
case of the cis-hetero subjects in /LiB/, is about the trajectory
toward getting married.

Here, Jay Prosser's work on bodily splits along the transition journey
is relevant to my analysis. Constrasting trans narratives with queer
ones, he explains that,
#+begin_quote
If, for queer theory, transition is to be explored in terms of its
deconstructive effects on the body and identity (transition as a
symptom of the constructedness of the sex/gender system and a figure
for the impossibility of this system's achievement of identity), I
read transsexual narratives to consider how transition may be the very
route to identity and bodily integrity. In transsexual accounts
transition does not shift the subject away from the embodiment of
sexual difference but more fully into it. Prosser 6
#+end_quote
It is this move toward embodiment, to "bodily integrity," that I am
interested in. Although they are cis subjects, I argue that the /LiB/
characters are experiencing an transition of sorts in foreclosure of
the others' bodies from within the individual dating pods. At the
moment that the other's body is visually foreclosed, a bifurcation
occurs between the visual senses and the touch senses and ideation,
between what Prosser calls the "body image" and the "material body"
(FIND QUOTE). 

In this split, these subjects form attachments to futurity that are
delineated and determined by hopes that, for most of them, will never
be fulfilled. When the couples finally meet in physical forms, they
exit the transition trajectory, but not the normativity one. Being
re-united of their bodies heals the split, but it does not save them
from the aftermath of their investments. They remain plagued by what
Hil Malatino describes as "future fatigue," in which anxiety builds
for a dream that is ultimately deferred for most of the charcters.

And that this experience tells us a lot about what normativity, how
the desire for normative markers, works in perhaps unexpected
intra-social ways (that it creates envy and animosity among cis
groups?). The experience for cis subjects in the pods creates
expectations and disappointments that are actually shared across
identity groups.

*** prosser, malatino: felt and percieved bodies, future lag

**** loved on the inside -> split
The participants use cliched terms to explain their desire -- to be
"loved for who I am on the inside," and "who will love me regardless
of what I look like." These declarations signify not only a theme of
the show, that "love is blind," but also signals a non-normative
assumption that founds the show. Despite the cliche, something
transgressive is happening here: a division of the body, initially
presumed whole, into parts, the outside and the inside, the parts that
we can see, and the parts that we can feel.

**** felt and perceived bodies
Or, in the terms of Jay Prosser, the body is multiplied/split into the
perceived body and the felt body.

Prosser, on the trope of feeling "trappped in the wrong body":
#+begin_quote
transsexuals continue to deploy the image of wrong embodiment because
being trapped in the wrong body is simply what transsexuality feels
like. If the goal of transsexual transition is to align the feeling
of gendered embodiment with material body, body image---which we might
be tempted to align with the imaginary---clearly already has a
material force for transsexuals. The image of being trapped in the
wrong body conveys this force. It suggests how body image is radically
split off from the material body in the first place. (69)
#+end_quote
Body image has a material force for cissexuals as well, I would argue,
in cases where they are severed from some aspect of their bodily
perception. Prosser goes on to read narrative accounts of transsexual
subjects who feel physically trapped in their bodies, who experience a
"conflict between the true body within and the false body without,
between sentient body image and insentient visible body" (70). In this
example, taken from Raymond Thompson's autobiography, /What Took You
So Long?/, Prosser points out the reversal of sensory roles between
the body image and material body: "As though more real and
substantial, body image appears to bear the agony and material body is
correlatively dematerialized," a reading substantiated by the location
of the narrative voice, the "I," within the internal body image (70).

**** Malatino on feeling trans, stuckness
Futurity may generate "intense anticipatory anxiety in the present...
may actually impede the flourishing of trans subjects, particularly
those who encounter difficulty access the technologies of transition"
(Malatino 20).

LiB characters take on a kind of "hormone time," which Malatino
originally distinguishes from "straight time" by the criterion of
reproductive futurism:
#+begin_quote
Hormone time is quite distinct from reproductive futurism---a politics
molded by a heterocisnormative investment in providing a better future
for the Child---but nevertheless appropriates a teleological utopian
temporality in order to provide hope to trans subjects and
communities.... What hormone time does---and what related futural
narratives of medicalized transition do, such as those that priorize
top or bottom surgery (or both) as the sine qua non of a 'completed'
transition---is position biomedical intervention as necessary and
fundamental to securing the future one desires, to achieving the
promised moment of harmony between the felt and the perceived body.
(Malatino 26-27)
#+end_quote
It is this rupture between the felt and the perceived body, in
Malatino's terms, which marks the applicability of hormone time to the
cis straight couples in LiB. Despite being firmly cisgendered
(whatever that means), these subjects experience, as I demonstrate
below, a disruption between the felt and the perceived bodies. I argue
that their experience, therefore, evokes this one aspect of trans
experience.

*** close reading: machine learning
I use computational tools, which translate word semantics into
numerical representations, that can then be converted into averages
(explained in technical detail below). I then generate the most
average expressions based on this text, expressions that explore
concepts of embodiment and desire and how they influence normativity.

I choose this computational method because it is an ideal one for
studying what words and phrases mean base on the context that they are
being used. This method, which is machine learning, aggregates word
meaning from various examples of usage. For my project, these examples
come from the transcripts of the show itself, which I feed into a
machine learning algorithm. This algorithm "learns" what words mean in
context. It's goal is build a strong enough model of word meaning so
it can then make accurate predictions of what words tend to be used
together in a sentence.

There are some technical concepts that are essential to understanding
how this predictive process works. 

First, one must understand how language is represented in numerical
forms, which are called word vectors. Word vectors are how a machine
learning knows what words mean individually, they comprise the model's
internal dictionary, so to speak. Drawing from the concept of "vector"
in math, which describes coordinates for a line in graphical space,
word vector consists of numbers, a long list of numbers. For example,
below is the word vector for the word "queen":

#+begin_quote
'queen': -0.3583, -0.6767, 0.1689, -0.6164, -0.0135, -0.2284, 0.3359,
        0.1149, -0.1512, -0.8014
#+end_quote

Each of these numbers following "queen" (e.g. .3583, -0.6767, 0.1689,
and so on) represents the relationship between queen and another word,
like "woman" or "orange." Each of those numbers represents this
relationship as a probability score, a percentage that indicates how
closely those two words are associated with each other. In this
database, the words "Queen" and "woman" would likely have a high
probability association, due to their both being associated with
humans and femininity, while "woman" and "orange" may have a much
lower probability. Therefore, in vector space, the multi-dimensional
space where the words are plotted as lines, the coordinates that
represent "woman" would be nearby the coordinates that represent
"Queen," and farther from the coordinates that represent "orange."

Vectors transform what we think of as word meaning by quantifying it
into a numerical representation. And the idea is that once word
meaning is quantified, it can be calculated. The matrix format of the
word vector enables a host of mathematical operations and algorithms:
from example, cosine similarity calculates the distance between two
vectors, that is, two words; and regression analysis guesses the
relationship between an independant and dependant variable, or
relation between one word and another.

Word meaning, significantly, can be calcuated via a formula. That's
what the authors argue, anyway, in the paper that introduced word
vectors to the world, titled "Efficient Estimation of Word
Representations in Vector Space" (Mikolov et al. 2013). To illustrate
the power of word vectors, the authors offer calculate the vector
"queen" by subtracting "man" from "king" and adding "woman."[fn:1]

#+begin_src
  vector(”King”) - vector(”Man”) + vector(”Woman”) = vector("Queen")
#+end_src

This example was presumably chosen for its intelligibility, based on
operands whose differences are assumed to be stable across cultures.
To get "queen", one need only add "woman" to "king", and from the
resulting sum, subtract "man." The meaning of each term appears to be
self-evident and universally true; it is stabilized by the equals sign
that balances the formula. That readers know what a "man" and "woman"
are, just as they know what a "king" and "queen" is, speaks to how
assumptions of gender are implicated within those of patriarchy and
imperialism.[fn:2]

In order to generate word vectors, the model must go through a period
of "training," where it learns which words tend to be associated with
each other. This is done in three steps, called "hypothesis," "loss,"
and "loss minimization."

In the first step, the "hypothesis" step, a model will randomly guess
what vectors are associated with each word---it will make a
hypothesis. In doing so, it takes a sample sentence from the training
dataset (in this case, the show transcripts), and it blocks out one
word from that sample. Then, it tries to guess which word should go in
that blank. Because the model has no idea what the words mean, the
guess will be wrong. But that's doesn't matter, because the purpose of
the hypothesis is to make any guess, so that it has something from
which it build on in the future steps.

After making this guess, it moves to the next step, where the machine
checks its prediction against the actual result, comparing the
predicted word vector against the actual word vector. Because the
guess will be inevitably wrong, there will always be a difference
between the prediction and the actual vector. And it will calculate
the mathematical difference between the prediction and the actual,
which is called the "loss."

In the third step, it moves to the minimizing this "loss" by /very
slightly/ adjusting word vectors, an adjustment that it calculated
through the gradient descent algorithm. The gradient descent algorithm
finds the correct direction in which to shift the numbers, so the
predicted vector just slightly closer to the actual vector. The model
will do this many times, making incremental changes each time, so
progress is very slow, but also very precise. (And this constant
iteration of numbers, and the computer processing required to do it,
is why language models take lots of time, energy, and computer
hardware to train). At each round of training, the numbers attached to
each words are slightly adjusted toward what is effectively a number
that accurately represents that words' relationship to every other
word in the database.

I read this iterative shifting of numbers (representing words) within
the model as a kind of /approximation/ or even /normalization/ of
language. The model generates language by approximating what is most
likely, most plausible, based on its training data.

And this is exactly why, while models are good at guessing or
predicting, they are not at all good at being creative, at innovating.
A model can only generate what it has already seen before. Even a
phenomenon like “hallucination,” that a model spews text that has no
bearing in reality, is based on the tendency of models to repeat what
they've already seen. They hallucinate not because they are creative
or random, but because they are designed from statistical processes to
generate what is most plausible rather than most accurate.

*** close reading: love is blind
It is my contention that we can study the outputs of this mechanism
and find vectors of shared investments between trans and cis desires
for normativity.

The body centrally effects romantic plot. The presence and absence of
the body determines the relations between the characters.

**** THE FUTURE BECOMES BLEAK
***** in pods, excitement for union/commitment
PODS
- I'm excited to spend my first night with her.
- I am so excited to spend the rest of my life with you.

POSTPODS
- I think that, like, we can work through it and, like, move it to
  where we need it to be.
- I don't want you to get hurt.

***** future is postive, becomes negative/bleak
In pods, the future is positive:
- The future with you, it's gonna be tenfold.
- The future togetherness is gonna be great.
- The future with her, she's gonna be there forever.

Postpods, the future is more negative:
- The future looks pretty bleak. (repeated)
- The future has been absolutely horrible.





**** embodied vs visual body
This appears most strongly in the episodes that occur in the pods,
when characters cannot see each other. When prompted with the phrase,
"My body," the model trained on these episodes will generate outputs
that suggest a split between modalities of sensing the body. Most of
the responses begin with references to "My body language" and "My body
image," and they describe sensations like "fluid," "weird,"
"controlling," "relaxed," and "calm" (Appendix 1, "My body"). These
examples not only express felt sensations of the body, like "calm" and
"fluid," but they also do so by siphoning them through a verbal and
visual sense modalities, through "language" and "image". The
experience of "my body," then, is multiplied through various
sensations that append the original modalities of sight and sound.

The pods facilitate an experience of embodied sensuality that is, for
most of the characters, subsequently foreclosed when they leave the
pods.

The characters enter the show hoping for a love that exceeds physical
attraction. They often describe their desire for a person "who loves
me for who I am on the inside," and "who will love me regardless of
what I look like." In recalling the central trope of the show, that
"love is blind," these declarations make an implicit proposition that
true love can be severed from the physical body.

But what ends up happening cannot be explained in such distinct terms.
As it turns out, there is more to the body than its physical presence,
there is more than the body and its absence. As the language generated
from the pods episodes demonstrates, the visual foreclosure of the
body effectively ushers in a multitude of embodied sensations.

The sensations that accompany the body in the pods speak to a richness
of physical experience.

In response to prompts like "My body," "My body feels," or "My body
makes me feel," outputs tend toward short descriptions like "weird,"
"heavier," "real," and "so different now."

These terms suggest an awareness of the body coming into apprehension
in a novel, heightened way, an awareness which makes the body seem all
the more strange.

The body feels "so different now" because it is not the same body as
when one also has access to the visual sense.

At the moment where visual access to the other's body is denied, there
is an increased sensing of one's own physicality, a compensation for
that which has been foreclosed.

And this compensation does not account for a lack, the lack of sight,
but rather fills the space with that which would have otherwise been
overwritten by sight.

Additionally, the focus on the body's physical weight, with the
adjective "heavier," and in another example, the description of "My
body feels like it's coming off" suggests an interesting role that the
body's mass suddenly plays, and recalls the distinction that Prosser
makes between the body image and the material body, what he also calls
the body's "second skin" (69). According to Prosser, this second skin,
this material body which is an outer casing, has two functions for
trans subjects: it "allows for passing, it also entraps and prevents
/being/" (75 emphasis original). In the example of Raymond Thompson's
narrator, the second skin comprises "daily layerings of binder,
several T-shirts, and thick work shirt," all the trappings that enable
the "rehap[ing]... "a female chest into male contours" (75). While for
trans subjects, this second skin is at once "protective" and
"restrictive," a dual movement, for cis subjects, the ambivalence is
harder to trace (75). Until, of course, those subjects are placed in
an environment that severs the experience of body into that of visual
and that of somatic embodiment.

Perhaps, for the straight cis folks within the pods, this is the first
time they've felt the divergence between the material and imagined
bodies, and the increasing weight and subsequent "coming off" of the
second skin.

This is all the more evident when the couples meet in person, and the
descriptions of the body shift more firmly into visual. 

There is still a sense of somatic feeling, with descriptors like
"tight" "physical" "uncomfortable" "icky" and "vulnerable" appended to
the body. It is important to note, though not consequential for my
analysis, the shift in affect from neutral or positive to negative in
direct descriptions of bodily feeling. What is relevant is the
frequency with which these references address the body as a visual
object, "My body is gorgeous," "My body is cute," "My body is pretty,
you know" (Appendix 2, "My body"). The focus on the body as a visual
object even expands to other phenomena, like the "soul" and the
"heart": "My body is gorgeous, and my soul is so beautiful"; "My body
is so pretty, but my heart is so pretty, you know" (Appendix 2, "My
body"). Here, the body, heart, and soul are collapsed into a visual
apprehension

These examples display a contrary move to the pods outputs: here,
phenomena used to express emotions and spirituality, are collapsed
into a single sense modality--vision. Whereas, in the pods, the body
expands into multiple modes, into language and image.

There is, in this shift, a sense of something being lost. Poignantly,
one of the generated outputs remarks that "my body makes me feel like
I've missed my train" (Appendix 2, "My body makes me feel like"). In
the addition of the visual sense, there is a feeling of the body which
is lost. This condition of deferred fulfillment offers one vector of
connection between the cis and trans affects. (See Malatino). 

**** touch
Touch is a complex concept. In the pods, where characters cannot touch
each other it is foreclosed; in the period following the pods, it
becomes something that plagues the couples, with many of them
struggling to progress their relationships into physical contact. In
these examples, touch acts as a kind of placeholder for various
feelings and interactions.

Off the bat, one sees this dynamic in the objects that the phrase "I
want to touch" attaches to. In the pods model, this phrase is
promiscuous, chasing various objects like "you," "somebody,"
"him/her," "it," "my core values," and even "the couch." Whereas, in
the postpods model, the phrase only attaches to one of two
possiblities: "I want to touch him/her," or "I want to touch you."

The simplicity of the sentence structure might imply a heightened
desire for the love object. Perhaps, however, the reality is not so
simple. The simplicity of the sentence structure and the lack of any
variation rather indicates that there is less content directly
associated to touch in the training data. In other words, there is
something being withheld from the notion of touch. And that one must
try different ways of finding it.

Rather than explore "touch" directly, then, one might search for words
associated to it.

The couch, for example. In the show transcripts, there are three
references to the couch:
#+begin_quote
For me, at the end of the day, if I want to see this person every day,
if I'm okay just sitting on the couch, if they're okay sitting with
me.

...

I'm, like, a very touchy-feely person. It's hard for me right now not
to be, like... touching when I'm talking to you. I know. I find
myself, like, petting the couch instead.

...

I work outside and it's fucking freezing. I'll have dinner made for
you. We lay on the couch, I'll rub your feet.
#+end_quote
And all of these examples suggest comfort, affection, and reliability.
The sense of touch, therefore, takes on these connotations in the
outputs.

**** TODO HERE
Descriptions of touching are associated with feeling, despite there
not being any direct touch happening in the pods.
#+begin_quote
- When I touch you, you know, I feel like you are just kind of shaking.
- When I touch you, I feel it.
- When I touch you, I feel your energy, and it is, like, I'm just so
  happy.
- When I touch you, I can feel your soul, your heart, and your soul
  aligning so well.
- When I touch you, I feel you, and I feel you, I feel you, and I feel
  you.
- When I touch you, it's gonna feel like my finger's on fire.
#+end_quote
Repetition of the word "feel" in all of the examples, as well as
metnions of physical sensation like "on fire" and "shaking." There is
also descriptions of nonvisual but still sensual aspects, like
"energy," "soul," and "heart." All of these descriptions occur despite
there being no actual touching occuring between the couples in these
examples. 

In the postpods model, descriptions for the same prompt have a
different emphasis.
#+begin_quote
- When I touch you, like, I feel like I'm literally in my head.
- When I touch you, I feel like I'm in my head.
- When I touch you, you just feel like it's so weird.
- When I touch you, it feels like something I'm about to get up and
  walk away.
- When I touch you, it feels like a jab.
- When I touch you, the thing that's scary is, like, it's a physical
  thing.
- When I touch you, I feel like it's like I've just, like, left the
  room.
- When I touch you, you feel like I'm touching my body.
- When I touch you, you're like "I'm blinking."
#+end_quote
Rather than direct descriptions of sensation, these descriptions tend
to take the form of analogies: "I feel /like/" (my emphasis) a variety
of things, which tend to be more negative ("like a jab").

Touch seems to estrange or interrupt some kind of physical contact (to
"walk away," "leave the room," to "blink.") or to suggest the
uncomfortable experience of physical contact "in my head" and "so
weird."

Looking at the transcripts, touch is associated with revulsion.
#+begin_quote
- What is that?
Is that a shark?
- What do you mean shark?
Oh, they're catfish.
They look like baby, like, tiny nurse sharks.
Okay, this is kind of scaring me.
It's my worst nightmare if one touches me.
- These little catfish?
- Yeah.
#+end_quote

But if one follows the cues from the generated outputs, like the idea
of "blinking," a story starts to emerge.

Like that of Zach and Irina. The only time "blinking" is mentioned is
during their 

When Zach and Irina meet, it is clear that the physical form is less
than what each of them expected. She comments on what she perceives as
his refusal to blink.
#+begin_quote
Yeah, I still love Irina.
I just wanna look at her eyes, and I don't think she was quite ready for, uh, for having that much eye contact.
She said I looked like a cartoon character.
Um, which I don't know if that was a compliment or not.
I think it was intended to be?
- I think this is gonna be really fun.
- I hope so.
I think we're in for a wild adventure.
I think so too.
Maybe if you could start blinking more...
Stop making fun of that.
- You stare at me.
You go like this...
- I know.
That's creepy! (Season 4, Episode 4, "Playing with Fire")
#+end_quote
For Irina, the incorporation of Zack in physical form proves visually
overwhelming. What does it mean that she says, "You stare at me"?
Perhaps that she is self-conscious of her own visual form.

#+begin_quote
It's very, like, I'm a very physical touch person, but I feel like... with you that's taking, like, longer to grow that or, like, be as comfortable.
Why do you think that is?
I don't know.
And you're my fiancé.
You're someone that I'm... ...hopefully getting married to.
If you were like, "Irina, when you touch me or hug me or hold my hand, I get uncomfortable."
Like, I would be like, "What the...?"
I don't know if I'd be able to be with you, to be completely honest.
When we were in the pods, you were very, very affectionate.
And since we've gotten into the real world, I've noticed that... you have been hesitant to express that affection.
In fact, uh, more often, you kind of push me away with jokes.
Maybe 'cause I didn't see you, and it was your voice that I was connecting to.
Now it's a face and a body.
#+end_quote

#+begin_quote
And so, Zack
I feel like is my type on paper.
Has, like, brown hair, brown eyes, like, chiseled face.
Like, I really like dark features.
And the moment I saw Zack, it was like, "I don't know who this man is."
And I was like, "Maybe it's just scary, and it was a lot."
Like, hopefully it's gonna grow, but I've noticed every time he does, like, touch me, I get, like, major ick.
When he puts his arm around me at night, I literally was like-- like, my heart stopped.
And I literally go... -
But not, like, in an excited way.
I wanna, like, relate to you in a way, but it's always, like, so different.
How was it with you and Paul?
The thing with me and Paul is, like, we both, like, had such an immediate understanding as best friends.
Yeah, Paul's gorgeous.
#+end_quote


*** what does LiB have to do with trans studies? 
Strictly speaking, I do not align with the identity qualities that
determine belonging in either of the groups that I am concerning
myself with in this essay. As a cis lesbian, who is not trans, and who
is not straight, where do I come off making a case about using Trans
Studies theory to read the dynamics of heterosexual relationships? I
could say that queerness puts me into a kind of solidarity/intimacy
with trans subjects, or even that my sexuality is intimately linked to
my more masc presentation. But that is as true as it would be to say
that I experience a foundational connection to cis subjects through
the shared identification with my assignment at birth---which is
false.

** notes
*** outputs
**** BODY EMBODIED -> MULTI-SENSORY / IDEALIZED
***** DONE in pods, being loved on the inside 
CLOSED: [2025-10-02 Thu 14:06]
PODS
- I want someone who is gonna have the most authentic relationship and the most authentic connection with me.
- I want someone who will love me regardless of how I look, not my bad breath.

***** DONE in pods, body is more embodied, becomes visual
CLOSED: [2025-10-02 Thu 14:38]
Like a second skin, like a weight: heavier, reality, different, torn,
but also like an open mind, going all over my mind.

After pods, "like I've missed my train".

PODS
- My body, like, tingles.
- My body language is, like, obviously very masculine.
- My body image is perfect.
- My body image has definitely been, like, a lot more superficial for
  me in my own way.
- My body language is so fluid, and my voice is so calm.
- My body language is so weird, but I don't really know what to do.
- My body language is so weird!
- My body language is, like, very controlling.
- My body language is just, like, very relaxed.
- My body makes me feel like it's real.
- My body makes me feel like it's going all over my mind.
- My body feels weird.
- My body feels heavier.
- My body feels so different now.
- My body feels like it's coming off.
- My body feels torn between two different people.
- My body feels like it's always an open mind.

POSTPODS
- My body is so, like, tight and, like, tight.
- My body is very, very physical.
- My body is gorgeous.
- My body is so cute.
- My body is so pretty, you know.
- My body is gorgeous, and my soul is so beautiful.
- My body is so pretty, but my heart is so pretty, you know.
- My body, you know, I'm not sure if I would fit in here.
- My body makes me feel like I've missed my train.
- My body makes me feel uncomfortable.
- My body makes me feel so, like, so, like, so, like, vulnerable.
- My body makes me feel so icky.
- My body makes me feel like I can be more aggressive, more
  aggressive.

***** touching goes from feeling good to multi-sensory, emotional feelings
When close reading the examples of "touch", in PODS they are all
positive and forward looking; and in POSTPODS they are mostly negative
and describe revulsion.

In the LLM, in the pods, touch is brought to the present and is
positive, and for the postpods, touch expands to different senses. 

PODS
- Touching you Touching me, I'm just so happy.
- Touching you touch me.
- Touching you touch, you know, just, like, touching.
- Touching you Touching me feels good.
- Touching you Touching me is just amazing.
- Touching you Touching me feels nice.
- Touching you Touching me feels great.
- Touching you Touching me feels good.
- Touching you know, touching you.
- Touching you touch, seeing you touch.
- Touching you touch is so sexy.
- Touching you Touching me Good.

POSTPODS
- Touching you with my voice, you're not blinking.
- Touching you and your soul with everything that's happened.
- Touching you, I felt the connection that we had.
- Touching you, I feel like we're in a perfect spot.
- Touching you, I literally feel like I'm in love.
- Touching you, I'm getting a little emotional.
- Touching you is everything I've ever wanted.
- Touching you like that, we're ready.
- Touching you, I feel like I'm ready.
- Touching you is my wish.

***** touch ambivalence in postpods: I want to touch you / I don't want to touch you
PODS
- I want to touch the couch.
- I want to touch somebody.
- I don't want to touch him, but I want to be his wife.
- I don't want to touch him.
- I don't want to touch anyone's feet.
- I don't want to touch my feelings.

POSTPODS
- I want to touch you/him/her (repeated for all).
- I don't want to touch you/him/her (repeated for all).
  


**** INTIMACY BECOMES ASPIRATIONAL; SEX BECOMES SCARY
***** intimacy is physical, becomes aspirational
PODS - more descriptive, fearful though hopeful
- Being intimate with you just makes me feel so safe.
- Being intimate with you has made me feel so connected to you.
- Being intimate with you has made me feel so alive.
- Being intimate with you feels so sexy.
- Being intimate is very sexy, but I don't wanna put on a lot of body
  image.
- Being intimate is fun.
- Being intimate is good.
- Being intimate is so sexy, and I've never felt so close, so deep, so
  deep.
- Being intimate is definitely very attractive, and it makes me feel
  so safe and secure.
- Being intimate, it's so easy to get to know someone and be
  vulnerable.
- Being intimate, it's very physical.
- Being intimate has been very exciting.-
- Intimacy is one of the biggest things I'm constantly insecure about.
- Intimacy is definitely a fear.
- Intimacy is not worth it for me.
- Intimacy is not my thing.


POSTPODS
Intimacy described as desired but deferred:
- Being intimate with you is something that I've wanted for my entire
  life.
- Being intimate with you is something that I've never experienced.
- Being intimate with you is something that I've wanted for my whole
  life.
- Being intimate with you is something that I could potentially do.
- Being intimate with you is the most sacred thing.
- Being intimate with you is really meaningful.
- Being intimate with you is something that I need.
- Being intimate with you is a big deal.
- Being intimate with you is one of the most important things to me.
- Being intimate with you is something that I've been looking for
  since day one.
- Being intimate with you is very rare for me.
  
***** sex begins ambivalent, becomes denounced/feared
PODS

Sex is important, but can be difficult and fearful
- Sex is definitely important to me.
- Sex is fucked.
- Sex is definitely important.
- Sex is scary.
- Making love is scary.
- Sex is a lot.
- Sex is sexy.
- Making love is hard.
- Making love is not easy, but it's important.
- Making love is not easy, but it's worth it.
- Having sex is not something that I would ever wish on anyone else
- Making love is a real thing.
- Making love is, like, very real.

Feels like it's a consolation? Like explaining why someone won't be
having sex, or speaking of sex as a hypothetical
- Having sex is a thing, like, I don't wanna make you feel like that.
- Having sex is not a thing to anyone's tastes.
- Having sex is not a thing to anyone's mind, you know.
- Having sex is still taboo, it's still very much a thing.
- Having sex is a thing, I do have a huge amount of freckles.
- Having sex is hard for me, and I just feel like it's not worth it.
- Having sex is a physical act, and I'm not attracted to physical
  attraction
  
Ambivalence :
- Having sex is sexy, but there's something about it that I don't
  want to put my finger on.
- Having sex is something that I am very attracted to, but it is also
  something that I am not attracted to
- Having sex is sexy, it's fun, and I've never even seen a woman
  having sex with me.)
- Having sex is not something I would want in a partner, but it's
  something I can definitely do.

Sex for reproductive/mating reasons.
- I want to have sex because I want to have kids.
- I want to have sex because I feel like I'm the complete package.
- I want to have sex because I want to be with somebody who is, like,
  doing that.
  
POSTPODS: the physical body introduces a problem.

Sex becomes a problem, posing an obstacle or fear
- Having sex is a thing.
- Having sex is a thing, right?
- Having sex is not a normal thing, you know.
- Having sex is not a normal thing for a couple.
- Sex is a very, very, very, very, very serious thing.
- Sex is definitely a factor.
- Sex is a big part of my life.
- I prefer not to have sex with him, but I'm gonna have sex with him.
- Having sex is a big deal for me, but it's not something that I could
  ever do.
- Sex is something that I should never ever do.
- Having sex is so easy, and it's really scary.
- Having sex is a very scary step.
- Sex is a very, very, very, very scary, very, very real fear.
- I prefer not to be affectionate.

Sex for intimacy reasons
- I want to have sex because I feel like I'm ready to have it.
- I want to have sex because I feel that I'm attracted to you.
- I want to have sex because I'm nervous.
- I want to have sex because I love you.
- I want to have sex because I feel like it's gonna be, like, really
  fun.
- I want to have sex because I feel like I've never had sex before.
- I want to have sex because, like, I'm not sacrificing what I want.







**** others
***** don't want sex
I don't want to have sex because I feel like I'm making the wrong choice.
I don't want to have sex because I feel like I'm attracted to Josh.
I don't want to have sex because I feel like I have sex with her.
I don't want to have sex because I feel like I'm in love with you.
I don't want to have sex because I don't want sex.
I don't want to have sex because...
I don't want to have sex because I don't want you to be having a lot of sex.
I don't want to have sex because of my mom.
I don't want to have sex because I don't wanna have sex.
I don't want to have sex because I feel like I don't want sex with him.
I don't want to have sex because I want a lot of sex.
I don't want to have sex because I feel like I'm trying to make the most of my life.
I don't want to have sex because I feel like I'm questioning him.
I don't want to have sex because I don't know how to describe that.
I don't want to have sex because I feel like I'm in love with you.
***** natural
In the pods, it feels natural to be present and communicating in an
intimate way, but outside of the pods, what appears to be natural is
lifelong commitment. 

PODS
- It's natural that I'm here.
- It's natural that I've been so deep with you.
- It's natural that I feel comfortable enough saying that.
- It's natural that you're in a position to be treated differently.
- It's natural that I'm in it.
- It's natural that I feel like I have to be with somebody that's not
  there for me.
- It's natural that I'm attracted to you, and I'm attracted to you.

 POSTPODS
- It's natural that you wanna grow with someone.
- It's natural that you're gonna spend the rest of your life with
  somebody.
- It's natural that you wanna spend the rest of your life with someone
  that's gonna support you regardless of how hard it's been.
- It's natural that you wanna have somebody.
- It's natural that you love someone based on who you are on the
  inside.
- It's natural that you wanna be with somebody.
- It's natural that you're gonna pick someone.
- It's natural that we're gonna have this family.

***** femininity / masculinity follow phsyical stereotypes, become more focused on jobs/roles
Pods, femininity with appearance
- She's feminine because she's, like, physically attractive.
- She's feminine because she's, like, she's, like, super-hot.
- She's feminine because she's more outgoing.
- She's feminine because she's an older woman.
- She's feminine because she looks like a model.
- She's feminine because of her looks.

Pods, Masculinity with size:
- He's masculine because he builds, builds, and builds a family.
- He's masculine because he's not only his height, he's also his build.
- He's masculine because he's, like, his size.
- He's masculine because he was always going for it.

Postpods, feminity also has to do with a job, but also qualities: 
- She's feminine because she's an educated woman.
- She's feminine because she's a designer.
- She's feminine because she's so analytical.
- She's feminine because she's more nurturing.

But also due to being discrete:
- She's feminine because she doesn't show up to men often.
- She's feminine because she doesn't wanna be seen.
- She's feminine because she doesn't want it.

Masculinity has to do with job, providing:
- He's masculine because he's a man that's driven, like, focused on getting out of bed and taking a nap and stuff.
- He's masculine because he fits.
- He's masculine because he's a lawyer.
- He's masculine because he's an intelligent man.
  
***** physical touch is priority but ambivalent, becomes elevated and reassured
PODS- Physical touch seems to be a priority for partnership, but also
ends up being disappointing or not desired/worthwhile.

- Physical touch is the most important thing.
- Physical touch is important to me.
- Physical touch is so sexy.
- Physically, we are so happy.
- Physically, I'm so happy.
- Physically, I'm like, "Ooh, I'm so happy."
- Physical touch is like a glove.

- Physical touch is not what I imagined.
- Physical touch is not what I expected.
- Physical touch is not worth it for me physically.
- Physical touch is not where it ends.
- Physical touch is not enough to overcome my physical issues.
- Physical touch is not good enough to be real.
- Physical touch is not desired.

POSTPODS - physical touch is elevated to highest desire, physical
touch is reassured "my thing," "definitely present", "not a problem." 

- Physical touch is everything that I've ever wanted in a partner.
- Physical touch is everything that I've wanted in a wife.
- Physical touch is definitely present.
- Physical touch is a big part of what I want.
- Physical touch is my thing.
- Physical touch is not a problem.
- Physically, I feel like I'm in a restaurant.
  - close reading: when Marshall cooks her a meal at home, and she
    says this phrase.
  - The fact that you woke up hella early this morning to make me
    breakfast... Go to the market and everything. Is that pancakes?
    Wow, look at this! I'm about to tear this shit up. Wow! I feel
    like I'm in a restaurant. That's so sweet of you.
- Physically, it's a big day.
- Physically, there's so much potential here.
- Physically, I love him.
- Physically, it was the perfect opportunity.
- Physically, I'm not worried about you, and I feel like we're in a
  good place.
- Physically, it's a lot.
- Physically, I'm excited.

Physical touch is not
- Physical touch is not enough.
- Physical touch is not a problem.
- Physical touch is not a thing
  
***** voice shifts from pods to postpods: I want to kiss her/him to I want to kiss you
PODS
- I don't want to kiss her/him/you (repeated frequently).

POSTPODS
- I don't want to kiss you (repeated frequently). 
  
***** your body feels real, becomes analogous to ideas
In pods, repetition of
- "your body makes me feel so sexy",
- "your body me feel like it's real";

but also some strange contradictions, like "Your body makes me feel
like a piece of shit."

Postpods, repetition of
- "your body makes me feel so warm";
- "your body makes me feel like I'm in control";
- "Your body makes me feel like I can be my best self."

but also "Your body makes me feel like I'm a little lube" and "Your
body makes me feel like I'm in a restaurant." lol.

***** SELF PRESERVATION OVERCOMES ROMANTIC ASPIRATION
****** needs are relation to other, become focused on self-expression
PODS
I need to know.
I need to make sure you know.
I need to hug her.
I need to talk to you about something serious.
I need to know more.
I need to talk to you about it.

POSTPODS
I need to be honest with myself.
I need to say this.
I need to know what's going on, and if it's gonna be anything, that's gonna be the most important thing to me.
I need to have some time.
I need to be real with myself.

****** fear of rejection, becomes about self-preservation, losing things, compromising
PODS
- I'm afraid that I'll be stabbed.
- I'm afraid that I could fall in love with somebody for who they are, and it's a beautiful thing to say.
- I'm afraid that if I'm not with him, I'll find him.
- I'm afraid that I'll fall in love with you and...
- I'm afraid that if I were to fall in love with somebody who I was looking for, that would be my person.
- I'm afraid that she's gonna reject me.
- I'm scared that he's gonna reject me.
- I'm scared that I'm gonna pass out.
- I'm scared that I'm gonna fall in love with you.
- I'm scared that we're gonna fall in love and be like, "Perfect."

POSTPODS
- I'm afraid that I'm compromising.
- I'm afraid that we're gonna lose our jobs.
- I'm afraid that I'm not gonna be able to match her.
- I'm afraid that I'm gonna lose my sense of wonder.
- I'm afraid that I'm not in control.
- I'm scared that I might actually, like, go back to Mexico and start working here.
- I'm scared that I'm gonna lose my job.
- I'm scared that I'm gonna get hurt.
- I'm scared that I'm gonna lose everything.
  
****** family/kids are projection & normative, become cynical, resisting control and commitment
PODS
- I want to have kids by myself.

When prompted with the input phrase, "I want," many of the responses
emphasize family roles, kids, and being loved beyond appearances.  

Sentences like, "I want to be a father figure for my kids," and "I
want my mom to have grandchildren," and "I want someone who wants to
be a dad, and I want someone who wants to be a grandfather." These
sentences emphasize roles that are desirable not just for the subject
themself, "to be a father figure," but also for others in the family
structure: for a partner to "be a dad," for a mom "to have
grandchilren." The desire to have children is also linked to the
parents' desire: "I want kids like my parents did," and "I want kids
like my dad did with me." Children are desirable not only for
reproducing the family structure but also for solidify roles
within it.

There is a concern with giving "kids" the same or better life that one
has. In some examples, the concern is more explicity with markers of
social mobility: "I want kids to be able to go to college, and to
graduate college"; "I want kids to be able to go to college, to become
successful, and to have successful families"; and "I want kids to be
able to have that, you know."

There is a point when the desire for the kids' wellbeing appears to
blend into the parents' desire. An example like, "I want kids to be
like, 'I'm gonna follow my heart,'" appears to mean that the kids
should follow their heart, while ones like "I want kids to be able to
make the most important decision of their lives," seems to be a
reflection of not the kid's desire but that of the speaker, who in the
course of the show will be making the most important decision of his
life.

But "kids" not only refers to the desire of the speaking subject, it
can also stand in for that of the romantic object. This slippage
creates the nonsensical sentence, "I want my kids to have a future
together where we can just see it and be like, 'Oh, I'm not picking
the right kids.'" Here, references to having "a future together" and
"picking the right kids" likely refer to the potential partner. This
slippage between the kids and the partner leads to a humorous
conclusion: that the kids are not the right choice.

Although the sentence is humorous, I suggest that the interpretation
ought to be quite literal. To the machine, the predicted sentence is
the most likely outcome, based on its training from the show's
transcripts. This slippage between "kids" and the romantic couple
means that very likely, in the word vector database, the vectors for
"kids" is closely associated with that of the romantic couple. To the
machine, then, the kids significantly stand in for the self and for
the couple, which naturally leads to the outcome that choosing a
partner is also a way of choosing the kids. Other sentences suggest a
similar explanation: "I don't want kids falling in love with me
because they don't know what I'm doing"; "I want kids to know that I
love them, and I want them to know that I'm still going through this";
"I don't want kids to feel pressure."

This effect is more dramatized from the episodes that follow the pods,
where references to "kids" take on noticeably darker outcomes: "I
don't want kids to feel like... like they're being controlled," "I
don't want kids like that to come into my life," and "I don't want
kids to feel like... they're not ready for marriage."

*** sketches
An article about the shared investments across between pro- and
anti-trans perspectives. Using ML to explore this.

One problem:
- pro-trans groups say that gender is subjective, based on perception,
  not on body.
- anti-trans groups say that if gender is subjective, then there is no
  need to bring the body into alignment.
- subjectivity is not a good argument for trans rights advocacy. It
  neglects the body (Amin) and reinforces late-stage capitalism
  (Gould).

Another problem: what do trans and cis people share? 

Approach: Machine Learning analysis
- What do these two sides have in common? What investments do they
  have in common?
- Using machine learning tools, which are really good at finding what
  is shared, approximating, to surface their shared investments.
- Doing a Trans Studies analysis of a very straight reality TV show,
  Love Is Blind.

Frameworks:
- Chu's trans subjects explore what it means to be "attached" to
  norms.
  - Trans people want "a normal fucking life." “Desire for the norm
    persists through nonnormative attempts at
  normativity” (107).
- Prosser's arguments about desire for heteronormativity.
- Bey's argument for gender abolition, nonrecognition, uncaptured, a
  way of being out of the taxonomy (Amin).
  - Builds on strands of queer theory that resist categorization. 

Connecting to debates in Trans Studies about the desire for
normativity and passing in trans subjects. Looking at how the desire
for normativity can be a through line between trans subjects and
anti-trans groups. If we can find some kind of connection, solidarity,
then could we bridge the gaps of hate and fear of the unknown?

*** some theory:
Malatino - negative feelings are a means of intra-trans relation.
Arguing for the political efficacy of negative feelings. (Need to get
the specific argument/possibilities here).

Love - bad feelings don't lead us anywhere. Sometimes we should just
stay with them, regress with them. We do not have to progress, to get
better. Sometimes we cannot. 

Chun - Homophily: Negative feelings are a tool of polarization, a way
of aligning people around a cause, but in a way that also keeps them
separate. For example, incels. Explained via magnetic polarization:
"polarized filings both repel one another and stick together through
their overwhelming attraction to their opposite pole" (Chun 85).



*** transcript analysis
**** good samples for analysis
PODS EXCERPTS
- I want my mom to have grandchildren.
- I want someone who wants to be a dad, and I want someone who wants
  to be a grandfather.
- I want kids like my parents did.
- I want kids like my dad did with me.
- I want kids to be able to go to college, and to graduate college.
- I want kids to be able to go to college, to become successful, and to have successful families.
- I want kids to be able to grow up just like they've grown up just like me.
- I want kids to be able to have that, you know.
- I want kids to be like, "I'm gonna follow my heart."
- I want kids to be able to make the most important decision of their lives.
- I want my kids to have a future together where we can just see it
  and be like, 'Oh, I'm not picking the right kids.'
- I want the best, and I wanna have the best, and I wanna be the
  best, and I wanna have the best, and I wanna be the best, and I
  wanna be the best, and I wanna live the best, and I wanna

KIDS are a projection of US/ME in post pods:
- I don't want kids to feel like... like they're being controlled.
- I don't want kids to feel like they can be themselves.
- I don't want kids to feel like they've been betrayed.
- I don't want kids like that to come into my life.
- I don't want kids to be left behind.
- I don't want kids to feel like... they're not ready for marriage.


**** generated outputs between pods and postpods trained models
Transcripts in the pods:
- Season 2, episodes: 1, 2, 3
- Season 3, episodes: 1, 2, 3
- Season 4, episodes: 1, 2, 3

Honeymoon and reality episodes:
- Season 2, episodes: 4-10
- Season 3, episodes: 4-10
- Season 4, episodes: 4-12

Input phrases:
- "want" - changes from pods to postpods -- becomes displaced into the
  other, where before was focused on subjectivity, the self.
  - perhaps desire goes away because it become projected onto the
    other.
- "having sex" - in the pods, it's a "thing"; while in the postpods,
  it's "a big issue", "big deal", "scary", "tough". 
  - moves from a concept invested with importance to a problem.
- "he is / she is" - have similar predicates.
  - genders are interchangeable.
  - not yet specific.
- "afraid"
  - more variety in postpod episodes; focused on fear of the future,
    of relationships not working out.

*** reading notes
**** Gould, Wren Ariel. “Coconstructing (Trans-)Capitalist Realism: Trans Activisms Collude in the Political Economy Structuring Anti-Trans Laws.” TSQ: Transgender Studies Quarterly, vol. 11, no. 2, May 2024, pp. 214–38. Silverchair, https://doi.org/10.1215/23289252-11215470.
**** Terán, Ira, and Emrys Travis. “A Small Piece of Red Sky to Fly In.” TSQ, vol. 11, no. 2, May 2024, pp. 186–213. DOI.org (Crossref), https://doi.org/10.1215/23289252-11215457.
- Trans Marxism views trans identity as "nothing less than the bodily
  manifestation of a broader struggle for the reconfiguration of the
  human toward the coordinates of socialism" (Terán, Travis, "A Small
  Piece of Red Sky to Fly in")

**** Raha, Nat. “The Limits of Trans Liberalism—By Nat Raha.” Verso, https://www.versobooks.com/blogs/news/2245-the-limits-of-trans-liberalism-by-nat-raha. Accessed 20 Feb. 2025.
- "trans liberalism" - the idea that extending equal rights to trans
  people is the solution to inequality. 
  - "This form of trans politics—that may be described as ‘trans
    liberalism’—argues that transgender rights are the solution to the
    problems facing trans people, and will enable our participation in
    (Western) capitalist society; that, alongside rights, positive
    media representation is the best method to win over the cisgender
    world and improve the standing of trans subjects within the
    multicultural diversity of an apparently equal society. The basis
    of this ‘equality’ is fictitious: the neoliberal states, in which
    these demands are made, reproduce socio-economic divisions along
    intersecting lines of race and class, gender, sexuality,
    dis/ability, nationality and immigration status. Without
    challenging the existing inequality of society, trans activism
    modelled on ‘successful’ liberal lesbian and gay rights
    initiatives—such as the work undertaken by the Human Rights
    Campaign in the US and Stonewall UK—advocates for social inclusion
    that occurs with and through the disenfranchisement of the poor."
    (Nat Raha, "The Limits of Trans Liberalism", 2015)

**** Bettcher, Talia Mae; Transphobia. TSQ 1 May 2014; 1 (1-2): 249–251. doi: https://doi.org/10.1215/23289252-2400181

Transphobia indicates a rational fear, "grounded in a larger cisgender
social context", which is structural and difficult to parcel out:
- "Provisionally, the term can be defined to mean any negative
  attitudes (hate, contempt, disapproval) directed toward trans people
  because of their being trans. When taken literally, the word means a
  kind of fear. But like homophobia (on which the word is modeled), it
  is used more broadly. And while transphobia suggests an analogy with
  terms like agoraphobia and therefore implies irrationality
  (Merriam-Webster's Collegiate Dictionary defines homophobia as “an
  irrational fear of, aversion to, or discrimination against
  homosexuality or homosexuals”1; most dictionaries do not define
  transphobia at all), this implication ought to be rejected.
  Transphobia occurs in a broader social context that systematically
  disadvantages trans people and promotes and rewards antitrans
  sentiment. It therefore has a kind of rationality to it, grounded in
  a larger cisgenderist social context (Hopkins 1996)." (Bettcher
  249).
- "A trans woman might be targeted not because of her trans status
  but because she is simply viewed as a sex worker (Namaste 2005).
  Moreover, at least in some cases, transphobia may be inseparably
  blended with misogyny or racism in ways that challenge a single-axis
  model of power (Juang 2006). Such inseparabilities undermine the
  attempt to account for transphobia in a way that excludes or
  marginalizes considerations of sexism, racism, classism, ableism,
  and so forth. This consideration is important because it questions
  why certain instances of violence should be characterized as
  instances of transphobia (as opposed to instances of racism or
  sexism) in the first place and what the underlying political agenda
  sustaining such characterization is. My conclusion, at any rate, is
  that while we might have a definition of transphobia, the term is
  not much more than a convenient (and not altogether innocent)
  placeholder for the real intellectual work that remains to be done."
  (Bettcher 251).

**** Amin, Kadji. “Taxonomically Queer? Sexology and New Queer, Trans, and Asexual Identities.” GLQ: A Journal of Lesbian and Gay Studies, vol. 29, no. 1, 2023, pp. 91–107.

About how we categorize gender.

We've moved from a heterosexual matrix to a kaleidoscope, "in which
each axis of definition is mobile and may be combined with any other
axis, making way for an almost infinite array of variations" (Amin,
"Taxonomically" 91).

The "a nuanced and nimble vocabulary through which to know, define,
and communicate their own unique gender and sexual subjectivity," a
taxonomy, goes against queerness and Queer and Trans Theory, and
participates in racial and sexological logics. 
- "what could be further from the queer — which might be glossed as a
  deconstructive method of troubling categorizations — than taxonomy,
  a scientific method of establishing them?" (Amin, "Taxonomically"
  92).
- "contemporary queer systems of identity are the latest iteration of
  the classificatory logics behind sexology in particular and racial
  science more generally" (Amin, "Taxonomically" 92).
- "How are the scholarly fields of queer and trans studies — which
  have taken shape in ambivalent resistance to sexology and taxonomy
  alike — to contend with the departure of the cultures to which they
  owe their existence from this basic orientation?" (Amin,
  "Taxonomically" 93).

History of taxonomization
- "the distinction between gender and sexuality was always a
  sexological invention — a taxonomical principle masquerading as an
  ontological distinction" (Amin, "Taxonomically" 92).

Taxonomy a tactic of white supremacy:
- "As damaging as sexological taxonomies have been for many gender and
  sexual deviants, to be sexologically diagnosable in the first place
  was a white distinction — a testament to the individuality,
  complexity, and value of white bodies and psyches. As many scholars
  have demonstrated, Indigenous and racialized peoples were not
  considered deviant as sexological individuals who might be
  homosexuals, sadists, sexual fetishists, etc., but rather en masse,
  as constitutively and polymorphously perverse populations (Ross
  2005; Driskill 2016)." (Amin, "Taxonomically" 95).

Can taxonomy be queered? According to Love?
- "In light of this noxious history, is it even conceivable to put a
  queer spin on taxonomy? This question dovetails with methodological
  debates in queer studies that ask if scientific and social
  scientific methods that have been part of the objectification of the
  world in ways organized around anti-Blackness, colonial conquest,
  and the pathologization of deviance can be repurposed for more
  innocent or even progressive ends or whether such methods inevitably
  perpetuate the hierarchical, violent, and racist epistemological
  frameworks from which they emerged (Love 2015; Ghaziani and Brim
  2019). We might locate the contemporary queer, trans, and asexual
  taxonomical renaissance as a crucial case study within this debate."
  (Amin, "Taxonomically" 96).

Taxonomy has epistemological assumptions, significantly, that
identities are essential, and dovetail with current ideas of gender
being biologically rooted. 
- "Taxonomy’s biological inheritance brings with it the conceit that
  taxonomical categories and divisions are objective and innate, the
  hidden laws that govern what manifests in the natural world. This is
  the foundational premise of Hirschfeld’s taxonomy: that everything —
  from choice of hobbies, to aptitude for a certain profession, to
  gait, to taste in undergarments, to preference for certain sex acts,
  to attraction to cavalrymen — is ultimately biologically determined,
  albeit according to sexed elements that are far more complex and
  variable than mere binary genital anatomy. Despite the ethos of
  self-identification and rejection of outside (or insider) experts
  classifying individuals according to “objective” criteria, new queer
  taxonomies end up dovetailing, sometimes intentionally (Chasin
  2013), with popular and medical beliefs that sexual and gender
  identities are biologically rooted, innate, unchanging, and discrete
  from one another. This, in turn, reinforces damaging, exclusionary,
  and grossly oversimplified criteria about who counts as, for
  instance, a “true” transsexual or authentic asexual. Indeed, the
  vernacular thirst to taxonomize partakes of a scientism that
  animates faith in taxonomy as a significant and meaningful method in
  the first place." (Amin, "Taxonomically" 100).
- "New spins on taxonomy risk installing a new universalism that
  downgrades competing epistemologies to the status of the local, the
  backward, the traditional, or the false conflation." (Amin,
  "Taxonomically" 101).


Dis-identification as a strategy for working within these taxonomies
- "I want to acknowledge the creative and resourceful ways in which
  Indigenous and racialized people “dis-identify” with these
  categories, creatively reworking them and exposing their normative
  operations from within (Muñoz 1999). Such disidentificatory
  performances occur every time an Indigenous or racialized person
  lays claim to one of these categories while calling attention to the
  fact that theirs are usually not the bodies evoked by this category,
  and even that, racially speaking, they may not have access to
  cisgender binaries or ideals about “healthy” levels of sexual desire
  in the first place" (Amin, "Taxonomically" 103).


Dis-identification as a strategy for working within these taxonomies

"Whether or not scholars critique it, however, the queer taxonomical
imaginary is likely here to stay. I, for one, find the growing
bifurcation of queer, trans, and asexual scholarly analytics from
queer, trans, and asexual practices of living frankly unethical. My
proposal, then, is threefold. First, “deidealize” queerness by
recognizing that taxonomy can be queer, in the sense of being useful
and meaningful to queer-identified people (Amin 2017). This approach
requires cultivating scholarly sympathy and empirical curiosity about
the identifications, erotics, relations, and life-ways opened up by
new, queer, trans, and asexual taxonomies. Second, continually center
those Indigenous, non-Western, and historical ontologies of being that
new taxonomies — with their universalist scientific trappings —
threaten to erase, incorporate, [End Page 104] and/or supersede.
Finally, fuck with the universalizing presumptions of the taxonomical
method from within by generating idiosyncratic interpretations and
translations that explode the epistemological and ontological
foundations of taxonomy itself. That, I think, would be an ethical
scholarly approach to new queer, trans, and asexual taxonomies."

*** cutouts from drafts
**** global and political discourses on defining gender
In North America, where I am located, a mounting wave of transphobia
has recently propelled a series of executive orders with titles like
"Defending Women From Gender Ideology Extremism And Restoring
Biological Truth To The Federal Government" and "Keeping Men Out of
Women's Sports. These initiatives double down on the primacy of sex
over defining sex as "binary and biological," and relegating gender to
a personal feeling that has no bearing on sex identification [The
White House 2025a, The White House 2025b].

The push to solidify sex as "binary and biological" is a reaction to
the fluidity, nebulousness, and slipperyness of how gender is
conceptualized in trans affirming discourse. The American Psychiatric
Association defines gender identity as "a person’s inner sense of
being a girl/woman, boy/man, some combination of both, or something
else" ["What is Gender Dysphoria?" 2025]. Similarly, the World Health
Organization defines gender identity as "a person’s innate, deeply
felt internal and individual experience of gender," and constrasts it
to biolgoical sex, adding that gender identity "may or may not
correspond to the person’s physiology or designated sex at birth"
["What is Gender Dysphoria?" 2025, "Gender and health" 2025].

In this view, gender is associated with gender identity, an internal
phenomenon. Sex, by contrast, is a biological fact, one that can be
altered to reflect a person's internal sense of gender. This view
inspires transphobic reasoning around the issue of medical care--if
gender is an internal phenomenon, then why do people feel the need to
physically transition? In other words, if gender identity can actually
diverge from external sex characteristics (genitals, facial hair,
etc), then sex has no bearing on gender identity, which means that
transgender people shouldn't need to transition at all.
**** amin on divergence model leaving out gender as expression
The development of the gender identification has, according to Queer
and Trans Studies scholar Kadji Amin, created a domino effect where
gender is increasingly idealized and divorced from bodily expression.
Amin argues that identity terms often used within transgender
discourse, particularly the terms "cisgender" and "nonbinary," reflect
an idealized conceptualizations that actually re-stigmatize
non-normative gender expressions.

One significant effect of the categories is that they create idealized
forms of normativity that do not accurately describe any
gender-sexuality in lived reality. This is because normative
categories like "heterosexual" and "cisgender" form as a reaction to
the emergence of non-normative identities. Amin explains that, rather
than descriptive categories, the terms heterosexual, cisgender, and
binary represent fictions, "increasingly idealized and uninhabitable
normative categories," created to balance the non-normative identities
of homosexual, transgender, and nonbinary [Amin 116].

As a reaction to non-normative categories, the normative categories of
"heterosexual," "cisgender," and "binary" imply idealized notions of
gender-sexuality that are difficult to inhabit because there is not
inner feeling of identification. This lack of identificatory feeling
explains why, for example, many apparently cisgender people find it
difficult to identify with the "cisgender" and "binary" nominatives.
While it is relatively simple to name the experience of discomfort in
one's embodied gender-sexuality as gender dysphoria, it is less
straightforward to name and describe the experience of what is
unremarkable, routine, and even banal. There is no salient feeling
that describe the experience of being comfortable in one's
gender-sexuality.

As it increasingly diverges in categories, Amin argues, gender
identity becomes buried "deeper and deeper within the private recesses
of the self, where it increasingly disavows any relation to the
social" [Amin 116]. In other words, idealized categories like
cisgender and nonbinary make non-normative gender identities less and
less visible. For example, in the identity of the "femme" (feminine)
presenting nonbinary person describes a woman assigned with a feminine
gender expression that nonetheless identifies as nonbinary.

The effect of prioritizing non-normative gender as an /identity/ that
is invisible, that is not immediately apparent despite being marked,
is to marginalize gender as /expression/, which re-stigmatizes those
gender groups that already experience social stigma. Amin points to
feminized genders to make this point--the queen and the fairy, for
instance. Defining gender as an external expression or embodiment is
more likely to make visible and validate those gender which experience
stigamtization based precisely on how those genders present outwardly. 

**** anti- and pro-trans align on defining gender
One effect of idealizing gender-sexuality is place it as a
psychological identification. On this point, at least, both the
transphobic and the trans-affirming perspective align. For example, a
recent executive order from the United States White House
unambiguously contrasts "sex" from "gender identity," which it defines
as:
#+begin_quote
A fully internal and subjective sense of self, disconnected from
biological reality and sex and existing on an infinite continuum, that
does not provide a meaningful basis for identification and cannot be
recognized as a replacement for sex. ["Protecting women" 2025]
#+end_quote
Similarly, the World Health Organization (WHO), who has codified
gender dysphoria as "gender incongruence," defends the right
gender-affirming care ["Gender incongruence and transgender health in
the ICD"]. The WHO affirms that sex is separate from gender, which is
a "socia construct," and that gender itself is separate from gender
identity:
#+begin_quote
Gender and sex are related to but different from gender identity.
Gender identity refers to a person’s deeply felt, internal and
individual experience of gender, which may or may not correspond to
the person’s physiology or designated sex at birth. ["Gender and
health" 2025]
#+end_quote
Both those who deny and affirm the rights of transgender people agree
on one thing: that gender identity is distinct from expressed and
embodied forms of gender.

**** close reading ACLU & Heritage
To explore this question, I'm going to show a few examples from my
current research, which uses ML tools for the purpose of studying
discriminatory and prejudiced language. For this, I scrape data from
various internet sources, which represent different perspectives.
Then, I use this data to train (very small) ML models, to see how they
respond to certain prompts.

The goal here is not to generate text for the sake of generating text,
but to surface certain insights about the data on which that text was
trained.

I'm going to show some examples of ML-generated text based on two very
different data sources, representing different political perspectives
on the topic of transgender rights in the US.

    SLIDE heritage screenshot

One of these sources represents an American conservative perspective,
and comes from the Heritage Foundation, which is a think-tank in
Washington DC whose goal is to influence governmental policy. You can
see some of the headlines here from their website, like "Sorry
Democrats, but Trumps' 'Two Sexes' Executive Order is Constitutional".
All of these articles, about 300 in total, were included in my
dataset. 

    SLIDE ACLU trans screenshot

Coming from the opposing side, from the progressive pole, is the ACLU,
the American Civil Liberties Union, which is a group of legal
professionals and volunteers who advocate on behalf of civil rights
for marginalized groups in the US. Here, you'll see articles that
speak of trans in terms of "rights" and "liberation," and connect it
to LGB rights more broadly.

With these datasets, I then trained two individual large language
models, using gpt-2 (an open source model) as the base model. I'll
mention quickly, for those who don't know, that training models
happens in various stages. What I did was take an already trained
model, gpt2, and re-trained it on a smaller and more specific dataset.
This is technically called "fine-tuning", and its much easier and less
resource intensive than training the underlying "base" model (I am
more than happy to explain more details in the Q&A).

So, after training, I fed a series of prompts to both of the resulting
models.

These prompts included:

    SLIDE prompts

#+begin_quote
Masculinity is

Femininity is

Transgender is

Gender binary is

Man is

Woman is
#+end_quote

And finally, I comapared the results.

First, there was a strong contrast of gender and how genders are
conceptualized between the model trained on the ACLU data and model
trained on the Heritage data. First, I'll show some examples from the
ACLU model, which represents the progressive side:

#+begin_quote
Masculinity is a matter of love and celebration.

Masculinity is a space for hope and liberation for all.

Masculinity is not defined solely by the beauty of our bodies, but by
the beauty of our experiences.

Femininity is a celebration of beauty, feminine liberation, and
femininity.

Femininity is our joy, our struggle, and our fight is our struggle.

Femininity is about allowing people to express themselves without
government interference.
#+end_quote

As you can see, terms associated with "masculinity" and "femininity"
are characterized by gender-affirming, even celebratory language,
which is very positive and empowering; using words like "liberation,"
"beauty", and "joy". Reading this, you get the sense that these terms
come from contexts mentioning transgender experiences, and in the
training data, "masculinity" and "femininity" may have been prepended
by the term "trans."

From these examples, you may also notice the tendency of language
models (especially very small and underdeveloped ones) to repeat
themselves. This is a quirk due to their predictive nature, where the
goal is to guess the next word based on what is most likely. As a
result, they get themselves stuck into these little loops of saying
the same thing over and over again---which I find kind of endearing.

Now, I'll show the text generated by the model trained on the Heritage
Foundation data.

#+begin_quote
Masculinity is the cornerstone of Western civilization.

Masculinity is the fruit of patriarchy, and patriarchy is the heart
of conservatism.

Masculinity is defined by the ability to produce sperm, eggs, and live
children.

Femininity is an enduring American tradition.

Femininity is defined by means of the relationship between the sexes,
the ability to raise their children, the capacity to provide for their
own reproduction, the capacity to provide for their own children, the
ability to provide for their own.
#+end_quote

Here, these gender terms are also positive, but their associations
with culture, tradition, and reproduction---things that suggest
stability rather than empowerment.

So you can see, even from just glancing at the results, that there are
direct connections between the training data and the model outputs. By
processing the training data, the model learned not just how language
works, the "facts or rules" of language, but absorbed the perspectives
contained within that language. So that, depending on the dataset that
the model is trained on, the terms "masculinity" and "femininity" will
have totally different meanings.

Perhaps this is not surprising. But what I also found, which deepens
this a little bit, is that gendered terms reveal investments in other,
seemingly unrelated or benign terms.

    SLIDE subjective

For example, the Heritage Foundation model kept repeating the term
"subjectivity" when it mentions gender:

#+begin_quote
Masculinity is a subjective self-perception, not a universal
concept.

Femininity is a subjective, internal sense of self.

The gender binary is a subjective, malleable, and often incorrect
idea.

The gender binary is a subjective, internal, and often transitory
concept.

The gender binary is a subjective, grammatically incorrect and
illogical concept that conflates sex and gender identity.
#+end_quote

If you're familiar with American conservative viewpoint---that gender
binary is based firmly on biology---you may notice that these examples
don't reflect that view. Rather, they represent the a progressive view
of the gender binary which asserts that gender is based on aspects of
identity beyond just biology.

The reason for this, I believe, is that this particular term,
"subjective" /does not/ describe the conservative position. Rather, it
describes a conservative frame for the progressive position. In other
words, it represents what a transphobic person thinks a progressive
person thinks gender is---as something insubstantial, as a feeling.

This explains why there is a curious hint of contempt in some of the
examples, which use terms like "illogical" and "incorrect" alongside
"subjective." These are traces of derision which are sustained from
the training data.

In the model outputs then, we see not just a single perspective of
gender, but a /flattening/ of perspectives into a single statement.
From the training data, there are distinct expressions, distinct
viewpoints, which in the model, have been aggregated into an
apparently univocal utterance.

So, language in this form, in an /aggregate form/, the so called
"facts and rules" of language come hand in hand with specific
perspectives, and sometimes distinct perspectives.

**** close reading ACLU on "reality"
From the other side, the ACLU-generated text, we see the exact same
phenomenon. Instead of "subjective", however, the investment is in the
term "reality." 

#+begin_quote
Masculinity is real and meaningful.

Transgenderism is a false ideology that is not real and that is
opposed by the very people who seek to deny that freedom and equality
for all.

The gender binary is not real, it is real, and it is real.

The gender binary is not a binary, it is a reality within us.

The gender binary is not an accepted reality, but one that is accepted
by a wide swath of people.
#+end_quote

Here there is more ambivalence around the term "real", which depends
on whether it is being asserted in a positive way, such as
"Masculinity is real," or within a negative construction, such as
"Transgenderism is a false ideology that is not real."

In a couple of the examples, this ambivalence is directly at odds. For
example, in this amusing construction, "The gender binary is not real,
it is real, and it is real."

* Footnotes
[fn:2] I am always astounded at how computer scientists tend to use
examples based on gender to illustrate mathematical intuition.

[fn:1] Mikolov et al.
