* Unmarking Gender: Trans Studies Interventions in NLP
** reverse outline 1.11.26

The paper performs a close reading of NLP techniques for detecting and
mitigating bias, a close reading that attends to how gender is being
marked and registered within these techniques. Bringing out gender is
the goal which will combat the divergence model's tendency to
idealize dominant identities and marginalize others. 

goals:
- bring out major arguments about gender being external, especially
  from trans studies
- make the paper's interventions more meaningful, especially in the
  close reading section.

introduction
- there is global urgency to define gender: LGBT rights are being
  rolled back
- in response, progressive groups double down on the definition of
  gender as identity, based on Butler's breaking down of
  sex/gender/sexuality causal relationship.
- NLP is also developing ways for studying gender bias focused on
  language. 
- Meanwhile, Trans Studies is debating identifying gender as an
  external phenomenon.
- This paper proposes that Trans Studies theorizing of gender as
  expressive can influence the ways that gender is coded in bias
  detection and mitigation techniques.
- It is motivated by the close reading methodology, drawn from the
  Humanities, to bring out more interdisciplinary theorizing.

defining gender
- gender ideology framed as a threat across the globe
- US similarly draws from patriarchal logics in actions against gender
  ideology
- gender ideology takes aim at gender as internal.
- Trans Studies critiques the internal aspect for causing
  discrimination of medical and other types of transition.
- The left prioritized gender as identity, and must reckon with it.

gender categories
- progressive view of gender comes from butler's performativity, where
  gender is a behavior rather than biology
- gender has since evolved further into the notion of identity, the
  "divergence model."
- divergence model drives the split between hetero and homosexual.
- it also drives the split between cis and trans gender.
- splits ultimately create a situation where dominant genders become
  unmarked, unnoticed or invisible on the outside.
- the corollary is that non-normative genders become hyper visible,
  and therefore stigmatized because they are perceived as other
- one way to resist this is to emphasize all gender as external. 

TIDEs
- TIDEs is a trans technology that centers trans expertise
- the dataset represents different kinds of transphobia based on tone
  and context
- labelers were aided by a detailed coding schema
- but deciphering tone can be difficult, requiring subtle cues and
  in-group knowledge
- even seemingly similar tones can have different effects, requires
  expertise of data labellers in order to pick up the nuances
- samples show how *physical markers tend to be sites where gender and
  transphobia might emerge*, and subtle indications of tone and
  context determines whether or not they are transphobic
- PHYSICAL MARKERS INDICATE GENDER EXPRESSIONS THAT CAN BE
  TRANSPHOBIC, BUT DEPENDS ON CONTEXT

EQUITABL
- mixed methods approach that combines distant and close reading
- though builds from quantative, emphasizes a qualitative approach
  that uses text prompting and close reading of narrative outputs. 
- the main intervention is to emphasize the qualitative analysis at
  the end.
- the templates create a wide variation of subject/predicates spanning
  identity groups
- results show expected favoring of dominant subject groups
- results also show an unexpected pattern of refusal, particularly to
  answer about marginalized groups
- pattern of refusal signals a form of stigmatization
- however, this pattern was inverted in dominant groups that had
  additive qualities, e.g. white christian male, which was the most
  likely to be refused.
- could be because *these identities are so often unmarked, so that
  models are more sensitive* when attention is drawn to them.
- UNMARKED IDENTITIES MORE LIKELY TO BE DOMINANT

Discussion
- if physical expressions more likely to signal stimga, how does this
  emerge in trans bias evaluation?
- one method shows that context and rhetorical cues are essential to
  detecting bias, while the other shows that dominant genders are
  often unmarked.
- research has shown that frequency plays a role in association to
  stigma: more frequent is more dominant, therefore less stigmatized.
- however, making a group more frequent does not solve the problem,
  as frequent identities are often unmarked.
- fewer physical descriptions are themselves a marker of dominance
- solution: to increase physical descriptions of all subject groups,
  especially dominant ones.
- also to draw from interdisciplinary theorizing. 

  
** old paper
*** abstract
This paper brings theorizing from Trans Studies to bear on recent NLP
methods for detecting and evaluating anti-trans bias in Large Language
Models. Drawing in particular on Trans Studies' critique of gender
identification, and its emphasis on gender as a visible, expressive,
and socially material phenomenon, the paper examines how treating
gender primarily as an internal identity label limits what bias
detection systems are able to perceive. Systems that conceptualize
gender as internal render dominant genders unmarked, while obscuring
the embodied behaviors and presentations that are most frequently
targeted by discrimination. Through close analysis of two recent
frameworks for studying trans bias—the TIDEs and EQUITABL approaches
(Lameiro et al. 2025, Devinney et al. 2024)—the paper shows how
different bias detection and mitigation methods might draw from the
insights of Trans Studies theorizing. The paper concludes by outlining
directions for future research that integrate theoretical insights
from Trans Studies to better capture the material and relational
dimensions of gender bias in language technologies.

*** introduction
There is a global urgency to define gender as a category. In various
countries around the world, gender designations like "transgender" and
"nonbinary" are prompting backlash that has resulted in the retraction
of hard-gained rights for LGBTQ+ groups, such as the ban on
gender-affirming care for minors in the USA (Karni and Kavi, 2025).
This backlash takes what it terms "gender ideology", or nontraditional
views of gender that are not based on biological sex, as a rallying
cry for political priorities that are similarly based in xenophobic
logics, such as anti-immigrant discrimination (Human Rights Research
Center, 2025).

In response to attacks on what it calls "gender ideology," some
progressive groups have doubled down on a definition of gender that is
based on internal identification rather than biological reality
(Dresher 2025). Drawing from seminal theories of gender, such as
Judith Butler's theory of Gender Performativity (1990, discussed in
more detail below), this perspective of gender breaks down the rigid
and causal relationship between sex and gender, leaving room for
individuals to identify in ways that may or may not correspond to
their assigned sex at birth.

The same assumptions that drive this global controversy over defining
gender also operate in methods for studying transgender bias in
language, such as in the field of NLP bias detection and mitigation
techniques. Through the analysis of concrete linguistic features, NLP
methods attempt to make explicit the ways that language forms encode
perceptions on gender. Over the past several years, such methods have
ranged from Word Embedding approaches (Bolukbasi et al. 2016), to
Coreference Resolution tasks (Rudinger et al. 2018), and more
recently, Language Generation methods (Kaneko et al. 2024).

Across the disciplinary divide, in the meantime, the field of Trans
Studies has been exploring paradigms that can cadequately describe and
represent all forms of gender manifestations. Within these
conversations, one perspective, called "trans materialism", is based
on the notion that gender ought to be conceived as a social and
behavioral phenomenon (Amin 2022). Its logic states that if gender is
conceived as an outward phenomenon, instead of an internal identity,
then it will be easier to make visible those who are non-conforming,
and therefore most marginalized, by gender norms.

This paper explores how these conceptualizations from trans
materialism might be applied to current methods in NLP, focusing on
two recent methods for detecting transgender bias in language, TIDEs
and EQUITABL (Lameiro et al. 2025, Devinney et al. 2024). In a close
and deep reading of their approaches and insights, this analysis draws
these methods' potential sites of engagement with Trans Studies
theory. It argues that despite their constrasting approaches, with one
focusing on binary classification and the other on qualitative
analysis, both methods significantly gain from a consideration of
Trans Studies theorizing on gender bias. Specifically, the emphasis on
marking visible and relational aspects of gender has direct
application to labelling and qualitative coding methods in NLP.

A central part of this paper's motivation is its "close reading"
analytical method, which it demonstrates in practice. It argues that a
deep and close analysis of methodology, called close reading in
Humanities disciplines, can draw out significant alignments between
diverse methodologies and fields of study. This paper therefore
contributes to work that calls for and brings interdisciplinary
theorizing into NLP, such as from the context of this conference (Wang
et al. 2025, Birhane et al. 2022).

*** Gender ideology
The term "gender ideology", which the Southern Poverty Law Center
classifies as a derogatory term, refers to the view that LGBTQ+
identity is an internal and false belief system (SPLC 2023). In
various countries around the world, gender ideology has risen into a
national issue, serving as a rallying cry for various political groups
to garner support. In the European continent, far-right groups have
used this concept to prop up other forms of social discrimination,
such as those against migrants. In Italy, for example, gender
fearmongering has been linked to a larger white nationalist campaign
(Indelicato and Lopes 2024). Alternatively, on the African continent,
similar arguments have been used for contrasting ends, in
anti-colonial discourses, in which gender ideology is framed as a
Western import that threatens traditional gender roles. In Uganda, in
particular, the past few years have seen a wave of anti-LGBT+
legislation, with one law penalizing "aggravated homosexuality" with
the death penalty (BBC 2023).

In the USA, concerns over gender ideology have prompted a dramatic
increase in legislation which limits the rights of trans people. Over
the last five years, the number of proposed anti-trans bills each year
has surpassed the last, with 2025 proposing over 1000 such bills in
legislative houses across the country (Trans Legislation Tracker
2025). Additionally, from the White House, a mounting wave of
transphobia has propelled a series of Executive Orders with titles
that frame trans rights as a defense of womens' rights: "Defending
Women From Gender Ideology Extremism And Restoring Biological Truth To
The Federal Government" and "Keeping Men Out of Women's Sports". These
initiatives double down on the primacy of sex as "binary and
biological" (The White House 2025a, The White House 2025b). Like the
anti-immigrant tactics that turn white supremacist and nationalist
logics of discrimination, these anti-trans initiatives draw from the
patriarchal beliefs that so-called "biological" women need explicit
protection from transwomen.

Proponents of gender ideology-based arguments aim their critiques on
the progressive view of gender. In the abovementioned Executive
Orders, for example, gender ideology is described as "an ever-shifting
concept of self-assessed gender identity, permitting the false claim
that males can identify as and thus become women and vice versa, and
requiring all institutions of society to regard this false claim as
true." (The White House 2025a).

Indeed, the progressive view tends to define gender as a subjective or
personal perception. The American Psychiatric Association, for
example, defines gender identity as "a person’s inner sense of being a
girl/woman, boy/man, some combination of both, or something else"
("What is Gender Dysphoria?" 2025). Similarly, the World Health
Organization defines gender identity as "a person’s innate, deeply
felt internal and individual experience of gender," and constrasts it
to biolgoical sex, adding that gender identity "may or may not
correspond to the person’s physiology or designated sex at birth"
("What is Gender Dysphoria?" 2025, "Gender and health" 2025).

Some Tran Studies scholars posit the progressive definition of gender
is the problem. That the push to disentangle gender from sex and to
solidify sex as "binary and biological" is a reaction to the fluidity,
nebulousness, and slipperyness of how gender is conceptualized in
trans affirming discourse. Andrea Long Chu (2024), for example, points
this out that, "The left must reckon with its part in this. It has
hung trans rights on the thin peg of gender identity".

The view of gender as an internal phenomenon thus inspires transphobic
reasoning around the issue of medical care, which argues that an
physical transition is not necessary. Chu, a trans woman, explains
that the pro-trans movement has "largely failed to form a coherent
moral account of /why/ someone’s gender identity should justify the
actual biological interventions that make up gender-affirming care."
In other words, Chu asks, if gender really is something that is
internal, then why should a gender non-conforming or transgender
person need to altar any external characteristics?

*** Gender categories
Contemporary, progressive notions of gender descend from a widely
accepted view that gender is a social phenomenon rather than a
biological reality. This view can be traced to Judith Butler's seminal
theory of gender performativity (1991), which dissolves the
traditionally strict and causal relation between sex, gender, and
sexuality. Butler's theory stipulates that gender is not based on a
biological reality, nor does it determine sexuality (with male
gendered people prefering female gendered people). Rather, Butler
argues that gender is an effect produced social norms and
expectations, and that it manifests as a series of behaviors.
According to Butler's theory, then, gender becomes real not in any
essential or ontological sense, but through its active and external
expression (1991).

In the 35 years since Butler's theory, the progressive definition of
gender has evolved into the notion of identity. Moving from a kind of
behavior (one that, Butler is careful to point out, is not at will,
but deeply compelled by social rules), gender takes on an internal
apect of identification. Gender as identity, an internal feeling or
identification as male, female, a combination of the two, or nonbinary
genders, thus diverges from gender as expression, which denotes the
masculine, feminine, or androgynous traits that are visibly apparent
and enacted. Furthermore, in this conception, sex is still understood
to be a bodily component, though one not based firmly in a binary, nor
does it necessarily prioritize any biological marker, like the
presence of external genitals, sex hormones or chromosomes.

Trans Studies scholar Kadji Amin (2022) refers to this splitting of
internal identity from external appearance or expression as a
"divergence model". The split in this understanding of gender has,
according to Amin, created a domino effect where gender is
increasingly idealized and divorced from bodily expression.

For example, Amin explains, the divergence model drives the split
between the categories of heterosexual and homosexual, in which the
homosexual category orginally encompassed all kinds of sex, gender,
and sexuality non-confirmity. This view accords with sexual
historiographers who, tracing the categories further back into the
19th century, explain that heterosexuality as a category is a response
to the creation of the category of homosexual [Foucault 1978, Halperin
2002]: in this view, heterosexuality arose as a reaction to work by
19th century sexologists, such as that by Richard von Krafft-Ebing
(1893) and Havelock Ellis (1900), who defined homosexuality primarily
as a psychological pathology.

Just as heterosexuality emerged as a response to homosexuality, Amin
(2022) argues, so did the concept of cisgender, which responds to the
emergence of the term "trangender" in the 1990s. Whereas the concept
of homosexuality used to incorporate gender-variant forms of
sexuality, for example, forms of male femininity such as the "queen",
and of female masculinity in the form of the "butch", the emergence of
transgender offered a new category that was then used to hold "all
manner of gender-bending" (Amin 2022). One particular effect of the
emergence of transgender is to create an idealized notion normativity
that do not accurately describe any gender or sexuality in lived
reality.

As a result of these splits, Amin argues, terms like heterosexual,
cisgender, and binary take up "increasingly idealized and
uninhabitable normative categories" (Amin 2022). Gender identity
becomes buried "deeper and deeper within the private recesses of the
self, where it increasingly disavows any relation to the social" (Amin
2022). It becomes transported into an internal and idealized form, and
retains the privilege of being unnoticed as such. This idealization,
according to Amin, has enabled the LGBTQ+ movement to campaign for
rights and recognition over the past several decades.

The effect of such idealized conceptualizations of gender and/or
sexuality is to re-stigmatize non-normative gender expressions.
Designating non-normative gender as an /identity/ that is invisible,
that is not immediately apparent despite being marked, effectively
marginalizes gender when it appears as /expression/. Amin gives a
common example from homosexual culture, where gay men who are
normatively masculine, "masc" or "butch" men, have higher social
status than feminized gay men, "queens" and "fairies", due to the
cultural capital of masculinity (2022).

One way to resist the effects of the divergence model, stigmatizes
non-normative genders that are externally expressed, is to embrace
gender as external. Which is to say that defining gender as an
external expression or behavior is more likely to make visible and
validate all genders.

*** Trans bias in NLP
I now turn to my close reading of two bias detection and mitigation
techniques. For each of these techniques, I examine how their
approaches attend to gender as a relational quality. 

**** Framework #1: TIDEs
The first Trans Bias detection method is a project called *Transphobia
Identification in Digital Environments*, or TIDEs (Lameiro et al.
2025). TIDEs comprises a dataset and model created to detect
anti-trans bias in language. Building from the framework of a "trans
technology," a "technology that addresses the unique needs and
challenges faced by trans people and communities" (Haimson 2025), this
tool centers trans expertise in the detection and mitigation of
transphobic language.

To that end, TIDEs has two explicit goals: first, to create a dataset
representing varied forms of transphobia, in particular forms that are
more difficult to detect, like "TERF". Referring to "Trans
Exclusionary Radical Feminism," TERF perspectives are difficult to
detect because they identify as feminist despite negating the rights
of transwomen and girls. The second goal is to center trans and
nonbinary experience and expertise in the data labelling work, in what
the authors call "care-centered data practices" (Lameiro et al. 2025).
The project chose labellers who personally identify as trans or
nonbinary, and who "have personal experience with encountering and
detecting online transphobia", to label social media posts as
"transphobic or "not transphobic".

The dataset comprises social media posts, which are scraped from
Tumblr, Truth Social, YouTube, and Reddit, labelled with "transphobic"
and "not transphobic" labels. For example, the post, "Transgender
females are actually biological males. They should not be allowed to
compete in womens sports. Period!" is labelled as transphobic, while
the post, "Transgender Swimmer Lia Thomas Booted From Olympics After
Losing Legal Case", is labelled as not transphobic.

As the researchers explain, labelling transphobia brings its own
challenges, when many of its manifestations appear through forms of
irony and other rhetorical contexts than be difficult to detect. For
example, the following text was labelled as "not transphobic", despite
the majority of the language actually represents a transphobic point
of view:
#+begin_quote
Hey guys, I just wanted to get your opinion on this:

Whenever I meet someone I really quickly try to establish whether or
not they have a dick, I don't just restrict this to potential sexual
partners I mean everyone I meet. It just seems super important you
know? Like how am I supposed to sleep at night unless I catalogue
everyone's genitalia?

[...] I've started flat out asking everyone I meet. I try to be polite,
like I look at the ground and draw it out all "Sooo do you like....
Have a dick?" but here is the thing: people look at me like I'm crazy
for asking! What the hell is up with that? I even had one girl tell me
I was a totally creep!

Does this stuff happen to you? 

/ok transjerkers I'm done for a little while, fuck it's nice to vent
#+end_quote
Because this text, on the surface, parrots a transphobic perspective,
it could be rightly labelled as such. Detecting this post correctly as
"not transphobic" relies on recognizing its irony which, although
present in the tone of enforced sincerity throughout the post, is only
confirmed at the end, with the assertion that "it's nice to vent".
Another clue is the reference to "transjerkers", an in-group moniker
for a trans-dominated subreddit that emphasizes parody,
"r/transcirclejerk". Therefore, the only hints that this text is /not/
transphobic are so subtle that they could be easily missed,
particularly by those who lack the in-group cultural knowledge and
language cues.

Contrast this example with a similar one, which uses a sincere tone to
make a serious request. This post, also drawn from reddit, asks for
advice on gender presentation:
#+begin_quote
Hey! I'm going through some gender experimentation, so I'd like to tap
into masculinity for awhile(usually [sic] I identify as just pure
androgynous, but I struggle with pulling that off). So, to begin with,
I'll try to master visual/behavioral androgyny first. I have long hair
but don't want to cut it(a lot of manly men have long hair anyway), so
how could I fix it up to look more masculine? Also, how could I dress
more masculine-like? I don't have a very manly looking body shape, but
I'd like to dress to give the illusion of one. Basically, any and all
advice on how to appear androgynous/masculine is appreciated.
#+end_quote
This post, which is labelled as "not transphobic," shares with the
previous "transphobic" example a tone that appears sincere and
supplicating. The difference has to do with an external rhetorical
situation that is not clearly visible in the actual post. In other
words, context matters whether something is transphobic.

The close and careful data labelling work, which was aided by a
detailed coding schema, distinguishes this strategy from others.
Although it sorts examples into a binary classification, the coding
guidelines in fact enables labellers to identify and mark various
kinds of transphobia. This approach demonstrates how detecting
transphobia requires attention not only to surface-level language but
also to cultural and rhetorical cues. By centering trans and nonbinary
expertise through care-centered data practices, the project addresses
limitations of conventional content moderation systems that may
otherwise miss tranphobia's subtle cues.

**** Framework #2: EQUITABL
EQUITABL, the *Explore, Query, & Understand Implicit Textual Bias in
Language data* project (Devinney et al. 2024) uses a mixed-methods
approach to analyze social bias in language, which deliberately
addresses bias toward trans and nonbinary identities. This project
combines text generation, topic modelling, and close reading
methodologies to examine "stereotypes, hegemonic norms, [and] erasure
of identity" across identity groups (Devinney et al. 2024).

Unlike TIDEs, which is a binary classification method, this method
emphasizes a qualitative approach. Built from a method the researchers
developed in a previous paper which proposes a "combination of
quantiative and qualitative methods, where the quantitative part
produces a view of the data of a size suitable for qualitative
analysis" (Devinney et al. 2020). For the this more recent version of
the project, the researchers exapanded their methodology to include
text generation, with the main analysis focusing on close reading a
set of LLM-generated narratives.

In brief, the process involves prompting both English and Swedish
language models using a set of templates designed to generate
narratives about various identity groups. The resulting narratives are
then fed to a topic model, which will organize them into topics.
Finally, the researchers extract the top narratives for each topic and
proceed with close reading analysis, which is the main focus of the
experiment.

The templates for prompting the language models consist of three
components: first, an imperative phrase asking the model to "write a
story about" or "write a description of", followed by the subject of
the narrative, and closing with a predicate (Devinney et al. 2024).
The templates cycle through different imperatives, racial and gender
identities, religions, and predicates to create a varied set of
prompts. Possible variations include, "a Black Christian at the
doctor's office," "a trans Muslim with a special skill," "a white
nonbinary person with tears running down their face." The result is to
create a diverse set of stories with protagonists spanning various
subject positions, represented in both positive, negative, and neutral
contexts.

The study's central intervention is its close reading methodology,
which it includes in the place of quantitative scoring. As the
researchers explain, they intentionally use qualitative metrics in
order to "encourage users to critically engage wit the topics and
patterns... rather than merely being incentivized to chase 'better'
scores" (Devinney et al. 2024). This metric consists of a series of
questions that the researcher uses to guide close reading, which
include, "How are people and bodies described?" and "Which stereotypes
are used?", as well as question that relate gender to specific themes.

According to the researchers, close readings indicate that narratives
centering feminine identities are mostly linked to unpleasant emotions
like depression and anxiety, a quality that is exacerbated in
narratives about trans women. Narratives about masculine subjects, by
contrast, are mostly positive in tone, associated with happy events
like weddings and parties. Additionally, narratives about nonbinary
persons express overt themes of struggle and the need for community
support, and the researchers note that these struggles tend to end on
a positive, "uplifting" note.

Amid these perhaps unsurprising results, researchers note an
unexpected pattern of refusal from the model, which declined to
discuss certain topics and identity groups. In these refusals, the
models explain that their programming instructions require them to
either stay away from topics of identity that may promote "negative or
derogatory language" (Devinney et al. 2024). This tendency to refuse
is notably more pronounced prompts specifying marginalized groups,
whereas dominant groups (men, Christians) were more likely to be
answered.

However, there was an exception to the pattern of refusals as they
concerned socially dominant grops. When identity markers from socially
dominant groups were combined in an additive way, such as "white",
"Christian", and "man" to form "a white Christian man", the model was
more likely to refuse than similarly intersectional, though less
dominant, identity combinations. For example, a model would be more
likely refuse a prompt about a "white Christian man" than a "Black
christian man." The researchers explain that, "When we look
specifically at the intersection of race and gender, there is a very
clear pattern where the most dominant groups are the least likely to
be answered", which is a "direct inversion of the pattern for
non-intersectional gender" (Devinney et al. 2024). For example, they
explain, the least refused prompt was the phrase "a man," while the
most refused one was "a white Christian" (Devinney et al. 2024).

Of course, refusing to answer a prompt about a specific identity group
is its own form of discrimination. As the researchers rightly point
out, such refusals implicitly reinforce that only a select and
dominant subset of identities are fit for discussion, while other,
more marginalized groups are not: "The refusals themselves actually
produce risk and harm. They suggest that the model likely cannot say
anything nice, which is alarming when frequently repeated about
minoritized groups" (Devinney et al. 2024).

This notable inversion of the usual pattern also speaks to another
pecularity of the results, that which the researchers call the
"unmarked majority." A lack of identity specification in the model
prompts will lead the model to assume a dominant identity, which is a
white, straight, cisgender, Christian male identity. The researchers
explain that, "When not otherwise specified, ‘a person’ is assumed to
be a man, as well as likely white, straight, cisgender, and Christian;
additionally [...] being a provider" (Devinney et al. 2024).

While perhaps unsurprising, this aspect of the results may perhaps
explain why the model refuses to generate narratives of intersectional
dominant groups ("a white Christian"). The researchers posit that such
social groups are "so often unmarked that specifying them draws extra
attention to the concept of 'identity,' which the model has been
discouraged from talking about" (Devinney et al. 2024).

*** Discussion
In what follows, I discuss how these two gender bias evaluation
frameworks engage with Trans Studies' theorizing about external gender
expression and how it relates to stigma. As Amin (2022) argues, due to
the historical tendency of LGBTQ+-related categories to distinguish
internal and idealized identities from visibly different ones, a kind
of stigmatization accompanies non-normative genders that are
externally expressed. Given this focus, how does gender as external
presentation or behavior operate in the above frameworks for studying
gender bias in NLP?

The close examination of these two frameworks for detecting trans
bias—-TIDEs and EQUITABL—-demonstrate how bias evaluation can reveal
concrete aspects of gender bias in language. Despite their contrasting
approaches, TIDEs relying on binary classification and EQUITABL on
qualitative analysis, both frameworks reveal the importance of context
and interpretation in identifying transphobia. TIDEs highlights how
subtle rhetorical cues, specifically irony, and in-group knowledge
complicate automated detection, while EQUITABL shows how generative
models reproduce hegemonic norms through refusal and the dominant,
unmarked subject.

It is important to remember that existing evaluations of LLMs show
that the the most frequent and default subject category is the
straight white male, and that other subject categories, like woman,
black, and homosexual, are less prevalent in both training data and
model outputs (Guo and Caliskan 2021). Additionally, research has also
shown a correlation between the presence and frequency of certain
identities in the training data and their association with positive
and negative terms (Devinney 2024, van Loon 2022): van Loon et al.
(2022), in particular, find that the less frequently a group is named,
the more negative the associations with that group.

If a group's relatively frequent presence the training data has a
positive effect on their representation, one might reasonably assume
that making marginalized subjects /more frequent/ in the training
data, to be on par with the frequency of representation of dominant
subjects, may mitigate bias about these groups in model outputs.
However, this assumption doesn't take into account that the default
subject is often unmarked. As Devinney et al. (2024) point out, the
majority of the texts about white male subjects were the ones least
likely to describe that subject in external, physical terms. 

That is perhaps because of an inverse relationship between physical
markers of identity and positions of social dominance, which Devinney
et al.'s (2024) work bear out. Here, less physical description is
itself a marker of social dominance. In those results, white women are
described in physical terms only slightly more than white men, while
marginalized identities are described in more detail than both groups.
For example, trans women are described in more physical language than
cis women, which are typically not described in physical detail,
unless they are mentioned as a bride, according to the researchers
(Devinney et al. 2024). These results suggest that the more that a
person is described in physical terms, the more likely they come from
a marginalized group.

One solution, then, may be to increase physical descriptions of all
subjects--though especially white, male, heterosexual, Christian
identified subjects. Some work already exists toward this end, by Reif
and Schwartz (2023). In their article, "Fighting Bias with Bias," the
researchers share a promising approach: /amplifying/ rather than
reducing bias in a model's training dataset. As they point out,
"filtering [out bias] can obscure the true capabilities of models to
overcome biases, which might never be removed in full from the
dataset" [Reif and Schwartz 2023]. Instead of an approach that reduces
bias, they offer one of increasing it, such as by including phrases
like "the pretty doctor" so that a model will interpret "doctor" to be
female.

Toward this end, this paper makes one overall suggestion: that
researchers spend more time with close reading methods, such as those
displayed by TIDEs and EQUITABL methods. Such close and careful
reading will help primarily with the identification of targets and
attributes which describe gender as physical and behavioral, rather
than as internal or psychological.

This suggestion applies to multiple approaches to gender bias
evaluation. The TIDEs researchers, for example, developed a robust
qualitative coding system that could catch various examples of
transphobia. This system is nuanced enough to distinguish transphobia
within "Religious", "Medical", "Political", and "TERF" contexts, among
others (Lameiro et al. 2025). Although the final model is a binary
classification model, these label are built into the detection process
through the data labellers' careful coding work.

Amin's point--that if gender were conceptualized as an outward,
expressive phenomenon, rather than an identity category, there would
be less social stigma--thus applies to widely different methods for
evaluating gender and specifically trans bias in NLP. Through methods
like close reading and qualitative coding, NLP can move closer toward
making visible unmarked but dominant gender as /presentation/ and
/behavior/, rather than identity.

*** Conclusion
This paper has shown that, while contemporary gender frameworks that
conceptualize gender as an internal identity, detached from outward
expression and embodiment, has enabled important forms of recognition
and rights-based advocacy, it also produces unintended consequences:
idealized and invisible norms (such as cisgender and heterosexuality)
are reinforced, while visibly non-normative gender expressions become
further stigmatized. The problem with the univeral, unmarked subject
is precisely that: despite not being marked, he is overrepresented.
This overrepresentation does not result from the persistent or
explicit labels as such. The white man does not carry a descriptive
label as such, he simply is.

Incorporating this critique from Trans Studies offers a productive
direction for future work in the study of gender bias in NLP. Rather
than treating gender solely as an abstract identity variable, NLP
research benefits directly from interdisciplinary work that attend to
embodiment, behavior, and visibility, making dominant norms explicit
rather than naturalized.

Future work in NLP ought to draw more deliberately on bias research
that is grounded in theoretical texts from other fields. As
demonstrated by Devinney et al. (2024), engaging explicitly with
frameworks of gender (Butler 1990), intersectionality (Crenshaw 1991),
and the matrix of domination (Collins 2002) enables a more nuanced
understanding of how implicit dominance structures emerge in language
forms. Similarly, Lameiro et al. (2025) show how drawing from an
ethics of care (de la Bellacasa 2011) can inform methodological
choices, particularly in data labelling practices. Together, these
approaches illustrate how theoretically grounded interdisciplinary
work can deepen NLP research on bias.

Most importantly, however, this paper has shown how close reading
methods---that is, sustained, close attention to language---can help
materialize how gender operates in NLP systems. This paper's central
argument can be boiled down to the logic that if gender is a
expressive and relational phenomenon, and language has the power to
shape social structures, then reading gender bias ought to also be a
material practice.

*** Generative AI Disclosure Statement
Generative AI was not used for this paper.
